name: 'Amazon CodeArtifact Auth'
description: 'Logs in the CodeArtifact for NPM(YARN) and Maven(Gradle). Only for D-SHARE Inc.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  region:
    description: 'AWS CodeArtifact Region'
    required: true
  domain:
    description: 'AWS CodeArtifact Domain Name'
    required: true
  owner:
    description: 'AWS CodeArtifact Owner Account Id'
    required: true
  duration:
    default: '900'
    description: 'Session duration'
    required: false
  repo:
    description: 'CodeArtifact Repository Name'
    required: true
outputs:
  registry:
    description: 'The URI of the CodeArtifact'
  auth-token:
    description: 'CodeArtifact auth token'
runs:
  using: 'node12'
  main: 'dist/action/index.js'
